### ISSUE TITLE
Problems with Python 3.6

### ISSUE THREAD

**Issue by wizzardx** [RussBaz/enforce#34]
This works fine with Python 3.5:

<pre>
import enforce

from typing import List

@enforce.runtime_validation
def test() -> List[int]:
    return [1,2,3]

test()

</pre>

But under Python 3.6 it has this error:

<pre>
  File "test.py", line 1, in <module>
    import enforce
  File "/tmp/x/py36/venv/lib/python3.6/site-packages/enforce/__init__.py", line 1, in <module>
    from .decorators import runtime_validation
  File "/tmp/x/py36/venv/lib/python3.6/site-packages/enforce/decorators.py", line 9, in <module>
    from .enforcers import apply_enforcer, Parameters, GenericProxy
  File "/tmp/x/py36/venv/lib/python3.6/site-packages/enforce/enforcers.py", line 7, in <module>
    from .types import EnhancedTypeVar, is_type_of_type
  File "/tmp/x/py36/venv/lib/python3.6/site-packages/enforce/types.py", line 5, in <module>
    from typing import Optional, Union, UnionMeta, Any, TypeVar, Tuple, Generic
ImportError: cannot import name 'UnionMeta'
</pre>

**Comment by RussBaz** [comment]
Python 3.5.3+ is now supported (including 3.6.0) in the dev branch. However, I have accidentally broken a backward compatibility with Python 3.5.0-3.5.2. I will try fixing it as soon as I manage to rollback to Python 3.5.2.

Thanks for waiting.
