### ISSUE TITLE
Set[] return type has errors

### ISSUE THREAD

**Issue by wizzardx** [RussBaz/enforce#33]
Working with 0.3.1, installed from PyPI

Example code:

<pre>
import enforce

from typing import Set

@enforce.runtime_validation
def test() -> Set[int]:
    return set([1,2,3])

test()
</pre>

Error:

<pre>
Traceback (most recent call last):
  File "/tmp/x/py35/venv/lib/python3.5/site-packages/enforce/nodes.py", line 403, in preprocess_data
    enforcer = data.__enforcer__
AttributeError: 'list' object has no attribute '__enforcer__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 9, in <module>
    test()
  File "/tmp/x/py35/venv/lib/python3.5/site-packages/enforce/decorators.py", line 123, in universal
    return enforcer.validate_outputs(result)
  File "/tmp/x/py35/venv/lib/python3.5/site-packages/enforce/enforcers.py", line 95, in validate_outputs
    if not self.validator.validate(output_data, 'return'):
  File "/tmp/x/py35/venv/lib/python3.5/site-packages/enforce/validator.py", line 26, in validate
    result = visit(validation_tree)
  File "/tmp/x/py35/venv/lib/python3.5/site-packages/enforce/utils.py", line 17, in visit
    stack.append(last.send(last_result))
  File "/tmp/x/py35/venv/lib/python3.5/site-packages/enforce/nodes.py", line 45, in validate
    clean_data = self.preprocess_data(validator, data)
  File "/tmp/x/py35/venv/lib/python3.5/site-packages/enforce/nodes.py", line 405, in preprocess_data
    return GenericProxy(data)
  File "/tmp/x/py35/venv/lib/python3.5/site-packages/enforce/enforcers.py", line 129, in __init__
    raise TypeError('Only generics can be wrapped in GenericProxy')
TypeError: Only generics can be wrapped in GenericProxy
</pre>

If we change Set to List then it works fine though:

<pre>
import enforce

from typing import List

@enforce.runtime_validation
def test() -> List[int]:
    return [1,2,3]

test()
</pre>

**Comment by hwayne** [comment]
Looks like the issue may be that Set isn't in TYPE_ALIASES:
https://github.com/hwayne/enforce/blob/master/enforce/types.py#L110

**Comment by RussBaz** [comment]
It is now fixed in the dev branch. Thanks for the reporting.
